name: Node.js CI

on:
  push:
    branches: [ "prep_for_ph_launch" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        redis-version: [4, 5, 6]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}
        redis-port: 6380
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}
        redis-port: 6381
    - run: source test/env/inMemory.sh && nyc --silent --no-clean ./node_modules/.bin/mocha --recursive "./test/*.js" --exit && source test/env/redis.sh && nyc --silent --no-clean ./node_modules/.bin/mocha --recursive "./test/*.js" --exit && nyc report
